### ISSUE TITLE
feat: Allow public Switchboard to be used as FT Receiver

### ISSUE THREAD

**Issue by NtTestAlert** [onflow/flow-ft#103]
### Issue To Be Solved
`FungibleTokenSwitchboard.PublicPath` exposes `{FungibleTokenSwitchboard.SwitchboardPublic}` which includes the `deposit` method,
but is not usable as `&{FungibleToken.Receiver}`

### Suggest A Solution
Change the linked type to `<&FungibleTokenSwitchboard.Switchboard{FungibleTokenSwitchboard.SwitchboardPublic, FungibleToken.Receiver}>` on 

https://github.com/onflow/flow-ft/blob/339da7554b457f4b0a1aed3d28c93b3f265f119c/transactions/switchboard/setup_account.cdc#L30

**Comment by joshuahannan** [comment]
@alilloig Was this completed? Can the issue be closed?

**Comment by alilloig** [comment]
yep!
