### ISSUE TITLE
Update contract import schema

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-ft#132]
### Issue To Be Solved
With flow-cli super commands came a new import syntax. The imports in this repo need to be reformatted as an example of up-to-date Cadence implementation consistent and compatible with other dev tools on Flow.

### Suggest A Solution
Update contract imports as described in [Flow CLI super commands docs](https://developers.flow.com/tools/flow-cli/super-commands#import-schema) and restructure directories in compliance with [super commands setup](https://developers.flow.com/tools/flow-cli/super-commands#setup).

Specifically, this means replacing the relative import schema of

```
import FungibleToken from "./FungibleToken.cdc"
```

To

```
import "FungibleToken"
```
  
### Context

This repo will be used as an example implementation for an upcoming grant wishlist item.

**Comment by joshuahannan** [comment]
This has been completed so I am going to close this
